### ISSUE TITLE
Support for Sonata across NeuroML/PyNN/NetPyNE

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/Networks_SIG#1]
Work to support the [Sonata format](https://github.com/AllenInstitute/sonata) is under way in:

NeuroMLlite: https://github.com/NeuroML/NeuroMLlite/blob/master/neuromllite/SonataReader.py
NetPyNE: https://github.com/AllenInstitute/sonata/issues/54
PyNN: https://github.com/NeuralEnsemble/PyNN/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sonata

Sonata is being used as a native format for the  Brain Modeling Toolkit, BMTK: https://github.com/AllenInstitute/bmtk.

**Comment by bcumming** [comment]
We have been working on implementing SONATA support in Arbor.

https://github.com/arbor-sim/arbor/issues/721

Hopefully we will have a working serial prototype (no feature complete) inside the next few weeks. From there we will try to implement it in parallel.

The big challenge that we see is loading models efficiently. As it stands, we have serious reservations about whether it will be suitable for loading large network models in parallel.

**Comment by pgleeson** [comment]
Thanks for the update. I'm overdue installing/investigating Arbor again, hope to try it out in the next week or two...

**Comment by pgleeson** [comment]
See bioRxiv manuscript on this work: The SONATA Data Format for Efficient Description of Large-Scale Network Models https://www.biorxiv.org/content/10.1101/625491v1

**Comment by pgleeson** [comment]
Since NeuroML/PyNN/NetPyNE support is documented in the [paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007696):

**The SONATA data format for efficient description of large-scale network models
Dai K, Hernando J, Billeh YN, Gratiy SL, Planas J, et al. (2020) The SONATA data format for efficient description of large-scale network models. PLOS Computational Biology 16(2): e1007696. https://doi.org/10.1371/journal.pcbi.1007696**

closing this issue for now and more specific issues can be opened
